### ISSUE TITLE
Dependency issue with conda install on Windows

### ISSUE THREAD

**Issue by kalebmoon07** [colomoto/colomoto-jupyter#13]
Hello,

The conda installation of versions>0.6.5 requires #[colomoto/espresso-logic-minimizer](https://github.com/colomoto/colomoto-jupyter/commit/9666f2673bb084df7fd86cfd74edd3530e1a05db) .
This package only contains a linux build and cannot be installed on a Windows PC.

Do you have any good idea to build a new conda package for Windows depending on colomoto-jupyter with a version higher than 0.6.5?

**Comment by pauleve** [comment]
I've pushed a windows package for anaconda. Can you confirm it works now?

(there is a simillar issue for macOS, so I'm keeping the issue open)
